config/routes.rb
ISurvey::Application.routes.draw do
  resources :authentications
  resources :surveys
  
  
  
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :registration => 'register' },
            :controllers => { :sessions => "sessions" }
            
  root :to => 'surveys#index'
  
  get   'surveys/:id/stats' =>  'surveys#stats'  
  post  'surveys/:id/take'  =>  'surveys#take'
  
  get   'stats/:user_id/:survey_id' => 'statistics#search'

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  
  def index
    @authentications = current_user.authentications if current_user
  end
  
  def create
    omniauth = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
    if authentication
      flash[:notice] = "Signed in successfully."
      sign_in_and_redirect(:user, authentication.user)
    elsif current_user
      current_user.authentications.create!(:provider => omniauth['provider'], :uid => omniauth['uid'])
      flash[:notice] = "Authentication successful."
      redirect_to authentications_url
    else
      user = User.new
      user.apply_omniauth(omniauth)
      if user.save
        flash[:notice] = "Signed in successfully."
        sign_in_and_redirect(:user, user)
      else
        session[:omniauth] = omniauth.except('extra')
        redirect_to new_user_registration_url
      end
    end
  end
  
  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_url
  end
  
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/views/authentications/_form.html.erb
<%= form_for(@authentication) do |f| %>
  <% if @authentication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authentication.errors.count, "error") %> prohibited this authentication from being saved:</h2>

      <ul>
      <% @authentication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :provider %><br />
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authentications/edit.html.erb
<h1>Editing authentication</h1>

<%= render 'form' %>

<%= link_to 'Show', @authentication %> |
<%= link_to 'Back', authentications_path %>

app/views/authentications/index.html.erb
<h1>Listing authentications</h1>

<table>
  <tr>
    <th>User</th>
    <th>Provider</th>
    <th>Uid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authentications.each do |authentication| %>
  <tr>
    <td><%= authentication.user_id %></td>
    <td><%= authentication.provider %></td>
    <td><%= authentication.uid %></td>
    <td><%= link_to 'Show', authentication %></td>
    <td><%= link_to 'Edit', edit_authentication_path(authentication) %></td>
    <td><%= link_to 'Destroy', authentication, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Authentication', new_authentication_path %>

app/views/authentications/new.html.erb
<h1>New authentication</h1>

<%= render 'form' %>

<%= link_to 'Back', authentications_path %>

app/views/authentications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @authentication.user_id %>
</p>

<p>
  <b>Provider:</b>
  <%= @authentication.provider %>
</p>

<p>
  <b>Uid:</b>
  <%= @authentication.uid %>
</p>


<%= link_to 'Edit', edit_authentication_path(@authentication) %> |
<%= link_to 'Back', authentications_path %>