config/routes.rb
ISurvey::Application.routes.draw do
  resources :authentications
  resources :surveys
  
  
  
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :registration => 'register' },
            :controllers => { :sessions => "sessions" }
            
  root :to => 'surveys#index'
  
  get   'surveys/:id/stats' =>  'surveys#stats'  
  post  'surveys/:id/take'  =>  'surveys#take'
  
  get   'stats/:user_id/:survey_id' => 'statistics#search'

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions, :dependent => :destroy
  has_one :statistics
  
#  has_many :choices, :through => :questions, :dependent => :destroy
  accepts_nested_attributes_for :questions, :reject_if => lambda {|q| q[:title].blank? }, :allow_destroy => true
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  
  before_filter :authenticate_user!
  
  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @surveys }
    end
  end
  
  def stats
    @stats = Statistics.where("survey_id = ?", params[:id]).first
    @survey = Survey.find(params[:id]);
    @result = @stats ? stats_of_percentage(@stats, @survey) : Hash.new(0)
  end
  

  def take       
    status = allow_user_take_survey && take_survey
    respond_to do |format|
      if status
        format.html { redirect_to action: 'stats', notice: 'Thank you for your participation.' }
        format.json { render json: @stats, status: :created, location: @survey }
      else
        error = @stats ? @stats.errors : "You have already taken this survey."
        @survey = Survey.find(params[:id])
        format.html { redirect_to @survey, alert: error }
        format.json { render json: error, status: :unprocessable_entity }
      end
    end
  end

  
  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @survey = Survey.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/new
  # GET /surveys/new.json
  def new
    @survey = Survey.new
    3.times do
      question = @survey.questions.build
        3.times do
          question.choices.build
        end
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/1/edit
  def edit
    @survey = Survey.find(params[:id])
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(params[:survey])

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render json: @survey, status: :created, location: @survey }
      else
        format.html { render action: "new" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /surveys/1
  # PUT /surveys/1.json
  def update
    @survey = Survey.find(params[:id])

    respond_to do |format|
      if @survey.update_attributes(params[:survey])
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url }
      format.json { head :no_content }
    end
  end
 
  private
    def take_survey
      status = false
      @stats = Statistics.where("survey_id=?", params[:id]).first
      s = Statistics.new(params[:statistics])
      if @stats
        new_records = @stats.records + s.records
        status = @stats.update_attribute(:records, new_records);
      else
        @stats = s
        status = @stats.save
      end
      return status
    end
    
    def allow_user_take_survey
      record = Record.where("user_id = ? and survey_id = ?", current_user.id, params[:id]).first
      if record
        return false
      else
        return true
      end
    end
    
    def stats_by_questions(stats)
      stats.records.reduce(Hash.new(0)){|m, r| m.tap{|ht| ht[r.question_id] += 1}}
    end

    def stats_by_choices(stats)
      stats.records.reduce(Hash.new(0)){|m, r| m.tap{|ht| ht[r.choice_id] += 1}}
    end
    
    def stats_of_percentage(stats, survey)
      questions = stats_by_questions(stats)
      choices = stats_by_choices(stats)
      result = {}
      survey.questions.each do |q|
        q.choices.each do |c|
          result[c.id] = choices[c.id] * 1.0 / questions[q.id]
        end
      end
      return result  
    end
    
 
end

app/helpers/surveys_helper.rb
module SurveysHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
  
  def link_to_template(f, object, association)
    fields = f.fields_for(association, object, :child_index => "new_placeholder") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    content_for((association.to_s.singularize + "_template").to_sym) do
      raw "<div id=\"#{association.to_s.singularize}_template\">#{fields}</div>"
    end
  end
    
  def new_question
    Question.new.tap{|q| 3.times{q.choices.build}}    
  end
  
  def new_choice
    Choice.new
  end
  
  def leading_choice(question)
    if(question.question_type == 1)
      raw check_box_tag("q[#{question.id}]", false) 
    else
      raw radio_button_tag("q[#{question.id}]", false) 
    end
  end
  

  
end

app/views/surveys/_choice_fields.html.erb
<span class="group">
  <%= f.label :content do %>
	Choice:
	<%= f.hidden_field(:_destroy) %>
	<%=link_to " X ", "javascript:return true;", :confirm => "Are you sure to delete this question.", :class => "delete" %>
  <%end%>
  <br />
  <%= f.text_area :content, :size => "90x2" %><br />
</span>

app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>
      <ul>
      <% @survey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="survey">
<p>
  <span class="title">Name:</span><br />
  <%= f.text_field :name, :size => 100%><br />
  <span class="title">Description:</span><br />
  <%= f.text_area :desc, :size => "90x6" %><br />
</p>

  <div class="questions">
    <span class="title question_link" data-confirm="Are you sure add new Question.">Questions</span> 
	<%= f.fields_for :questions do |builder| %>	
	    <%= render 'question_fields', :f => builder %>   
	<% end %>
  </div>

  <button class="title" type="button">Add Question</button>

  <div class="actions">
    <%= f.submit "Submit", :class=>"submit"%>
  </div>


<% link_to_template(f,  new_question, :questions) %>

</div>


<% end %>

<div class="template">
	<%= yield(:question_template)%>
	<%= yield(:choice_template)%>
</div>

app/views/surveys/_question_fields.html.erb
<div class="group">
	<%= f.label :title do %>
	Question:
	<%= f.hidden_field(:_destroy) %>
	<%=link_to " X ", "javascript:return true;", :confirm => "Are you sure to delete this question.", :class => "delete" %>
	<%end%><br />
		
	<%= f.text_area :title, :size => "90x3" %><br />
	<hr />
	<%= f.label :question_type, "Question Type:" %><br />
	<%= f.select :question_type, {" -- Choice Question Type -- " => 0, "Multiple Choices" => 1, "Single Choice" => 2} %>
	<hr />
	<div class="choices">
	<span class="title">Answer Choices</span>
	<div>
	<%= f.fields_for :choices do |builder| %>
	  <%= render 'choice_fields', :f => builder %>
	<% end %>
	</div>
	<button class="title" type="button">Add Choice</button>
	
	</div>	
	<% link_to_template(f,  new_choice, :choices) unless content_for?(:choice_template) %>
</div>  

app/views/surveys/edit.html.erb
<h1>Editing survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<%title "Vanceinfo Surveys"%>

<div class="view_surveys">
	<div class="title_bar">Survey</div>
	<ul class="list_surveys">
		<% @surveys.each do |survey| %>
		<li>
			<span class="title"><td><%= link_to survey.name, survey %></td></span>
			<span class="time"><%= survey.created_at.strftime('%Y-%m-%d %H:%M:%S') %></span>
		</li>
		<% end %>
	</ul>
</div>

<table class="list_survey" style="display:none">
<% @surveys.each do |survey| %>
  <tr>
	<td>.</td>
    <td style="width:600px;"><%= survey.name %></td>

    <td><%= link_to 'Show', survey %></td>
    <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
    <td><%= link_to 'Destroy', survey, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<% title @survey.name %>

<% cnt = 0%>

<%= form_tag({:action => "take"}, :name => 'take_survey_form') do%>

<%= hidden_field_tag("statistics[survey_id]", @survey.id)%>

<div class="survey">
  <div class="survey_title"><%= @survey.name %></div>	
  <div class="survey_info">
	<div class="page_status">Page: 1/1 Question No:<%= @survey.questions.size %></div>
	<%= @survey.desc %>
  </div>
  <div class="survey_body">
    <% @survey.questions.each_with_index do |q, i|%>
	<div class="question">
	  <div class="question_title"><%= i + 1 %>.<%= q.title %></div>

	  <div class="question_body">
		<% q.choices.each_with_index do |c, j| %>			
			<div class="question_item">
			<%= leading_choice q %>
			<%= hidden_field_tag("statistics[records_attributes][#{cnt}][_destroy]", true)%>
			<%# hidden_field_tag("records[#{@survey.id}][#{q.id}][#{c.id}]", 0)%>
			<%= hidden_field_tag("statistics[records_attributes][#{cnt}][survey_id]", @survey.id)%>
			<%= hidden_field_tag("statistics[records_attributes][#{cnt}][question_id]", q.id)%>
			<%= hidden_field_tag("statistics[records_attributes][#{cnt}][choice_id]", c.id)%>
			<%= hidden_field_tag("statistics[records_attributes][#{cnt}][user_id]", current_user.id)%>
			<%cnt = cnt + 1%>
			<%= c.content %>
			</div>
		<% end %>
	  </div>
    </div>
    <%end%> 
  </div>
  <div class="take_survey">
	<%= submit_tag("Take Survey", :class => "title") %>
	<%= submit_tag("View Result", :class => "title", :type => 'button', "data-link" => url_for(:action => 'stats')) %>
  </div>
</div>

<%end%>


<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/stats.html.erb
<div class="survey">
  <div class="survey_title"><%= @survey.name %></div>	
  <div class="survey_info">
	<div class="page_status">Page: 1/1 Question No:<%= @survey.questions.size %></div>
	<%= @survey.desc %>
  </div>
  <div class="survey_body">
    <% @survey.questions.each_with_index do |q, i|%>
	<div class="question">
	  <div class="question_title"><%= i + 1 %>.<%= q.title %></div>
	  <div class="question_body">
		<% q.choices.each_with_index do |c, j| %>			
			<div class="question_item">
			<%= j %>. <%= c.content %>
			<div class="progress"> 
				<div data-progress="<%= "%.2f" % @result[c.id] %>"></div><div class="progress_number"> <%= "%.0f" % (@result[c.id] * 100) %>%</div>
			</div>
			</div>
		<% end %>
	  </div>
    </div>
    <%end%> 
  </div>

  <div class="take_survey">
	<%= submit_tag("View My Selection", :class => "title", :type => 'button', "data-link" => url_for(:action => 'search', :controller => 'statistics', :user_id => current_user.id, :survey_id => @survey.id)) %>
  </div>
</div>

<%= link_to 'Back', @survey %>